owl_list = [
    {'img': '/static/img/xwork-1.webp',
     'tag1': '<span class="cat">Web Design</span>',
     'tag2': '<h3><a href="#">Разработка любой сложности</a></h3>'},
    {'img': '/static/img/xwork-2.webp',
     'tag1': '<span class="cat">Web Design</span>',
     'tag2': '<h3><a href="#">Разработка уникаьного дизайна</a></h3>'},
    {'img': '/static/img/xwork-3.webp',
     'tag1': '<span class="cat">Web Design</span>',
     'tag2': '<h3><a href="#">Контекстная реклама в Яндекс и Google</a></h3>'},
    {'img': '/static/img/xwork-4.webp',
     'tag1': '<span class="cat">Web Design</span>',
     'tag2': '<h3><a href="#">Обслуживание и наполнение контентом</a></h3>'},
    {'img': '/static/img/xwork-5.webp',
     'tag1': '<span class="cat">Web Design</span>',
     'tag2': '<h3><a href="#">Аудит и поисковое продвижение</a></h3>'},
]
