owl_list = [
    {'img': '/static/img/xwork-1.webp',
     'tag1': '<span class="cat">Web Design</span>',
     'tag2': '<h3><a href="#">Working Spaces for Startups Freelancer</a></h3>'},
    {'img': '/static/img/xwork-2.webp',
     'tag1': '<span class="cat">Web Design</span>',
     'tag2': '<h3><a href="#">Working Spaces for Startups Freelancer</a></h3>'},
    {'img': '/static/img/xwork-3.webp',
     'tag1': '<span class="cat">Web Design</span>',
     'tag2': '<h3><a href="#">Working Spaces for Startups Freelancer</a></h3>'},
    {'img': '/static/img/xwork-4.webp',
     'tag1': '<span class="cat">Web Design</span>',
     'tag2': '<h3><a href="#">Working Spaces for Startups Freelancer</a></h3>'},
    {'img': '/static/img/xwork-5.webp',
     'tag1': '<span class="cat">Web Design</span>',
     'tag2': '<h3><a href="#">Working Spaces for Startups Freelancer</a></h3>'},
]
